/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    seasons: Season;
    ageGroups: AgeGroup;
    teams: Team;
    fixtures: Fixture;
    results: Result;
    players: Player;
    news: News;
    events: Event;
    soccerSchoolSessions: SoccerSchoolSession;
    sponsors: Sponsor;
    galleryAlbums: GalleryAlbum;
    pages: Page;
    media: Media;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    ageGroups: AgeGroupsSelect<false> | AgeGroupsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    fixtures: FixturesSelect<false> | FixturesSelect<true>;
    results: ResultsSelect<false> | ResultsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    soccerSchoolSessions: SoccerSchoolSessionsSelect<false> | SoccerSchoolSessionsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    galleryAlbums: GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'teamManager';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * A football season (e.g. 2025/26). One season may be marked as current.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  /**
   * e.g. 2025/26
   */
  label: string;
  startDate: string;
  endDate: string;
  /**
   * Only one season can be current. Toggling on will unset others.
   */
  isCurrent?: boolean | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Editable list of age-group labels (U7, Girls U14, Vets, Walking Football, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ageGroups".
 */
export interface AgeGroup {
  id: number;
  label: string;
  /**
   * Lower numbers appear first (e.g. U7 = 7, U18 = 18).
   */
  sortOrder: number;
  defaultFormat: '5' | '7' | '9' | '11' | 'other';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  /**
   * e.g. Raw Skills U11 Lions
   */
  name: string;
  /**
   * URL slug, e.g. u11-lions-2025-26
   */
  slug: string;
  season: number | Season;
  ageGroup: number | AgeGroup;
  format: '5' | '7' | '9' | '11' | 'other';
  /**
   * Team manager (gets login & per-team edit rights).
   */
  manager?: (number | null) | User;
  coaches?:
    | {
        name: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  venue?: string | null;
  trainingTimes?: string | null;
  league?: string | null;
  crestImage?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sponsors?: (number | Sponsor)[] | null;
  /**
   * Link to the same team in the prior season (for history).
   */
  previousTeam?: (number | null) | Team;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description for accessibility/SEO.
   */
  alt: string;
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  url?: string | null;
  tier: 'principal' | 'gold' | 'silver' | 'bronze' | 'supporter';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixtures".
 */
export interface Fixture {
  id: number;
  team: number | Team;
  opposition: string;
  kickoff: string;
  homeAway: 'home' | 'away';
  venue?: string | null;
  /**
   * League / cup name.
   */
  competition?: string | null;
  status: 'scheduled' | 'played' | 'postponed' | 'cancelled';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results".
 */
export interface Result {
  id: number;
  team: number | Team;
  fixture: number | Fixture;
  scoreHome: number;
  scoreAway: number;
  scorers?:
    | {
        player: string;
        minute?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Player of the Match.
   */
  motm?: string | null;
  notes?: string | null;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Player listings. GDPR-conscious - hidden by default for under-18s.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  name: string;
  team: number | Team;
  position?: ('GK' | 'DEF' | 'MID' | 'FWD') | null;
  shirtNumber?: number | null;
  photo?: (number | null) | Media;
  /**
   * Only enable with parental/player consent (GDPR). Defaults to hidden.
   */
  showPublicly?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  /**
   * Optional - leave blank for club-wide news.
   */
  team?: (number | null) | Team;
  heroImage?: (number | null) | Media;
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  publishedAt?: string | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  startDate: string;
  endDate?: string | null;
  venue?: string | null;
  heroImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soccerSchoolSessions".
 */
export interface SoccerSchoolSession {
  id: number;
  title: string;
  dayOfWeek: 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun';
  /**
   * e.g. 10:00
   */
  startTime: string;
  /**
   * e.g. 11:00
   */
  endTime: string;
  /**
   * e.g. 4-7 years
   */
  ageRange: string;
  venue: string;
  /**
   * e.g. £5 per session
   */
  price?: string | null;
  capacity?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryAlbums".
 */
export interface GalleryAlbum {
  id: number;
  title: string;
  slug: string;
  team?: (number | null) | Team;
  season?: (number | null) | Season;
  date?: string | null;
  description?: string | null;
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from public forms (contact, trial, soccer school).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  type: 'contact' | 'trial' | 'soccerSchool' | 'sponsor';
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  team?: (number | null) | Team;
  ageGroup?: (number | null) | AgeGroup;
  status: 'new' | 'inProgress' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'ageGroups';
        value: number | AgeGroup;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'fixtures';
        value: number | Fixture;
      } | null)
    | ({
        relationTo: 'results';
        value: number | Result;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'soccerSchoolSessions';
        value: number | SoccerSchoolSession;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'galleryAlbums';
        value: number | GalleryAlbum;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  label?: T;
  startDate?: T;
  endDate?: T;
  isCurrent?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ageGroups_select".
 */
export interface AgeGroupsSelect<T extends boolean = true> {
  label?: T;
  sortOrder?: T;
  defaultFormat?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  season?: T;
  ageGroup?: T;
  format?: T;
  manager?: T;
  coaches?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  venue?: T;
  trainingTimes?: T;
  league?: T;
  crestImage?: T;
  heroImage?: T;
  description?: T;
  sponsors?: T;
  previousTeam?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixtures_select".
 */
export interface FixturesSelect<T extends boolean = true> {
  team?: T;
  opposition?: T;
  kickoff?: T;
  homeAway?: T;
  venue?: T;
  competition?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results_select".
 */
export interface ResultsSelect<T extends boolean = true> {
  team?: T;
  fixture?: T;
  scoreHome?: T;
  scoreAway?: T;
  scorers?:
    | T
    | {
        player?: T;
        minute?: T;
        id?: T;
      };
  motm?: T;
  notes?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  team?: T;
  position?: T;
  shirtNumber?: T;
  photo?: T;
  showPublicly?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  team?: T;
  heroImage?: T;
  excerpt?: T;
  body?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startDate?: T;
  endDate?: T;
  venue?: T;
  heroImage?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "soccerSchoolSessions_select".
 */
export interface SoccerSchoolSessionsSelect<T extends boolean = true> {
  title?: T;
  dayOfWeek?: T;
  startTime?: T;
  endTime?: T;
  ageRange?: T;
  venue?: T;
  price?: T;
  capacity?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  tier?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryAlbums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  team?: T;
  season?: T;
  date?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  team?: T;
  ageGroup?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Club-wide settings shown in the header/footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  clubName: string;
  tagline?: string | null;
  crest?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  safeguardingOfficer?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  clubName?: T;
  tagline?: T;
  crest?: T;
  heroImage?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contactEmail?: T;
  safeguardingOfficer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}